#!/bin/bash

# Utility to setup a new github repository
# gitsetup will clone the specified git repo and
#       set the local git user.name and user.email
#
# gitsetup requires values for  github-repo, user-name, user-email
#
# gitsetup can accept zero, 1 or 3 command line arguments
#
# Zero argument mode
#	gitsetup will prompt for github repo name
#	user-name and user-email will use script default values
#
# 1 argument
#	gitsetup will use $1 for the github repo name
#	user-name and user-email will use script defaul values
# 3 arguments
#	gitsetup will use $1 for the github repo name
#	$2 as value for user-name and $3 as value for user-email
#
#

echo "Git Setup Script"

if [ $# == 0 ]; then

    echo "Git Setup Script = Zero argument mode"

    echo "Enter Git User name?"
    read username

    echo "Enter name of the Git repository to clone?"
    read reponame

    echo "Enter user's email address for Git"
    read useremail
else
    username=$1
    reponame=$2
    useremail=$3

fi

# All 3 required variables should be present now

echo "Username = $username"
echo "Git Repo = $reponame"
echo "User email = $useremail"
echo
echo "Cloning repo https://github.com/$username/$reponame"
echo

#Importing Joe's script functionality to actually do the work

# clone repository for username, reponame

git clone https://github.com/$username/$reponame.git

# cd into new repo

cd $reponame
pwd

# set local GIt user.name and user.email

git config --local user.name "$username"
git config --local user.email "$useremail"
